-- AlterTable
ALTER TABLE "Restaurant" ADD COLUMN     "baseDeliveryFee" DECIMAL(10,2) NOT NULL DEFAULT 2,
ADD COLUMN     "deliveryFeePerKm" DECIMAL(10,2) NOT NULL DEFAULT 0.5,
ADD COLUMN     "deliveryRadiusKm" DOUBLE PRECISION NOT NULL DEFAULT 10,
ADD COLUMN     "minimumOrder" DECIMAL(10,2) NOT NULL DEFAULT 0;
